FROM rust:latest AS build

RUN apt-get update
RUN apt-get install sudo postgresql postgresql-contrib -y

WORKDIR /dolus

RUN cargo install diesel_cli --root . --no-default-features --features="postgres"

ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/dolus

# ============= cache dependencies =============
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
RUN mkdir src/
RUN echo "fn main() {}" > ./src/dummy.rs
RUN sed -i 's/src\/main.rs/src\/dummy.rs/' Cargo.toml
RUN cargo build --release

COPY ./Cargo.lock ./Cargo.lock
COPY ./build.sh ./
COPY ./src/ ./src/
COPY ./Cargo.toml ./Cargo.toml
COPY ./migrations/ ./migrations/

RUN bash ./build.sh

# ---------- Copy the built binary to a scratch container, to minimize the image size ----------

FROM ubuntu:20.04
WORKDIR /dolus
RUN apt-get update
RUN apt-get install curl libpq-dev -y

COPY ./migrations/ ./migrations/
COPY --from=build /dolus/target/release/dolus ./dolus

RUN ls -al /dolus

ENTRYPOINT ["./dolus"]
